# -*- coding: utf-8 -*-
"""pratical-2 daaa lab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120jZr3QEgzWbUl0yRnLi7uIbwpEDiqwb

linear search
"""

import time

def linear_search(arr, target):
    for i in range(len(arr)):
        if arr[i] == target:
            return i
    return -1


# User input
arr = list(map(int, input("Enter elements separated by spaces: ").split()))
target = int(input("Enter element to search: "))

# Measure execution time
start_time = time.perf_counter()

result = linear_search(arr, target)

end_time = time.perf_counter()
execution_time = end_time - start_time

# Display result
if result != -1:
    print("Element found at index:", result)
else:
    print("Element not found")

print("Execution Time:", execution_time, "seconds")
print("Time Complexity: O(n)")
print("Space Complexity: O(1)")

"""binary search

"""

import time

def binary_search(arr, target):
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2

        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            low = mid + 1
        else:
            high = mid - 1

    return -1


# User input
arr = list(map(int, input("Enter elements separated by spaces: ").split()))
target = int(input("Enter element to search: "))

# Binary search requires a sorted array
arr.sort()

print("Sorted Array:", arr)

# Measure execution time
start_time = time.perf_counter()

result = binary_search(arr, target)

end_time = time.perf_counter()
execution_time = end_time - start_time

# Display result
if result != -1:
    print("Element found at index:", result)
else:
    print("Element not found")

print("Execution Time:", execution_time, "seconds")
print("Time Complexity: O(log n)")
print("Space Complexity: O(1)")

"""**read** **me**

Linear Search is simple and works on unsorted data, while Binary Search is much faster for large datasets but requires sorted data. The execution time can be measured in Python using the time.perf_counter() function.
"""